version: '3'
services:
  db:
    env_file: .env
    image: postgres:11.2-alpine
  gems:
    image: busybox
    volumes:
      - gems:/gems
  node_modules:
    image: busybox
    volumes:
      - node_modules:/node_modules

  webpacker:
    build: .
    depends_on:
      - gems
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/node_modules
      - packs:/app/public/packs
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  app:
    build: .
    env_file: .env
    tty: true
    stdin_open: true
    depends_on:
      - db
      - gems
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/node_modules
      - packs:/app/public/packs
    ports:
      - "3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker

volumes:
  gems:
  node_modules:
  packs:
