# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

sum_amounts = (applied, other) ->
  a = parseFloat applied
  b = parseFloat other
  a + b

set_attributes = (el, attrs) ->
  for key, val of attrs
    el.setAttribute(key, val)

replace_id = (node, id) ->
  attribute_id_regex = /[\[\_]\d+[\_\]]/
  attributes = node.attributes
  if attributes != undefined
    for attr in attributes
      res = attr.value.match(attribute_id_regex)
      if res != null
        res = res[0].replace(/\d+/, id)
        attr.value = attr.value.replace(attribute_id_regex, res)

recursively_replace_children_attributes = (node, id) ->
  replace_id(node, id)
  for child in node.childNodes
    recursively_replace_children_attributes(child, id)

create_unique_row = (row) ->
  new_row = row.cloneNode(true)
  date = new Date()
  new_id = date.getTime()
  recursively_replace_children_attributes(new_row, new_id)
  return new_row

# render application of table row id
view_application = (table_row) ->


$ ->
  # TODO maximum precision, odd behavior with float, for example 0.33
  # sums up as 0.330000000004
  $('#application_amount_applied_for').on 'input', ->
    sum = sum_amounts $('#application_amount_applied_for').val(),
      $('#application_amount_other_sources').val()
    $('#application_amount_overall').val sum

  $('#application_amount_other_sources').on 'input', ->
    sum = sum_amounts $('#application_amount_applied_for').val(),
      $('#application_amount_other_sources').val()
    $('#application_amount_overall').val sum

  # create copies of rows generated by simple forms
  role_row = document.querySelector('.role_row')
  schedule_items_row = document.querySelector('.schedule_items_row')
  experiences_row = document.querySelector('.experiences_row')

  $('#add_member').on 'click', ->
    new_row = create_unique_row role_row
    btn = document.getElementById('add_member')
    btn.parentNode.insertBefore(new_row, btn)

  $('#add_schedule_item').on 'click', ->
    new_row = create_unique_row schedule_items_row
    btn = document.getElementById('add_schedule_item')
    btn.parentNode.insertBefore(new_row, btn)

  $('#add_experience').on 'click', ->
    new_row = create_unique_row experiences_row
    btn = document.getElementById('add_experience')
    btn.parentNode.insertBefore(new_row, btn)

  $(document).on 'click', '.remove_row', ->
    this.parentNode.remove()

  $(".clickable-row").click ->
      window.location = $(this).data("href")


